[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "imgrit"
description = "A tiny image processing library with k-means and Voronoi diagram."
version="0.2.1"
authors = [
  { name="Shingo TSUJI", email="shingo.tsuji@gmail.com" },
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
readme = "README.md"
dependencies = [
  "Pillow>=11.2.1",
  "numpy>=2.3.1",
  "scipy>=1.15.3"]
# numpy>=2.3 requires Python 3.11+
requires-python = ">= 3.11"

[project.optional-dependencies]
sklearn = ["scikit-learn"]

[project.urls]
Homepage = "https://github.com/tsjshg/imgrit"
Issues = "https://github.com/tsjshg/imgrit/issues"
